---
# handlers file for ppl-nginx
- name: Restart container
  docker_container:
    name: "{{ name }}"
    restart: yes
    state: started

# Reload nginx in container
- name: Reload nginx
  shell: |
    docker exec -i {{ name }} bash -c 'kill -HUP 1'
